name: udp
description: Lightweight, efficient, and easy-to-use UDP library for Dart. Supports Unicast, Broadcast, Multicast and Loopback communications.
version: 4.0.3
homepage: https://github.com/xenoken/udp
repository: https://github.com/xenoken/udp
issue_tracker: https://github.com/xenoken/udp/issues

environment:
  sdk: '>=2.12.0 <3.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
